### ISSUE TITLE
Bytes-like object required

### ISSUE THREAD

**Issue by Quinny** [paxos-bankchain/subconscious#23]
I'm trying to get subconscious working for a project of mine, but have run into a bit of a snag.  I have populated the Redis backed with some data, and I am attempting to display it via a Sanic web app.  The error I am getting is this:

<pre>
File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 465, in handle_request
    response = await response
  File "main.py", line 22, in wrap
    context = await f(*args, **kwargs)
  File "main.py", line 42, in index
    db = request.app.redis_connection, up = 1)]
  File "main.py", line 41, in <listcomp>
    recently_up = [host async for host in Host.filter_by(
  File "/usr/local/lib/python3.6/site-packages/subconscious/model.py", line 326, in filter_by
    for key in await cls._get_ids_filter_by(db, **kwargs):
  File "/usr/local/lib/python3.6/site-packages/subconscious/model.py", line 310, in _get_ids_filter_by
    max='{}{}\xff'.format(value, VALUE_ID_SEPARATOR).encode())})
  File "/usr/local/lib/python3.6/site-packages/subconscious/model.py", line 307, in <setcomp>
    temp_set = temp_set.union({x.partition(VALUE_ID_SEPARATOR)[2] for x in await db.zrangebylex(
TypeError: a bytes-like object is required, not 'str'
</pre>

The code which calls filter_by is as follows:

<pre>
@app.route("/")
@use_template("index.html")
async def index(request):
    recently_up = [host async for host in Host.filter_by(
            db = request.app.redis_connection, up = 1)]
    return {"hosts" : recently_up}
</pre>

And the model definition:

<pre>
class Host(RedisModel):
    ip_address   = Column(type=str, primary_key=True)
    scanned_at   = Column(type=str, required=True)
    scan_results = Column(type=str, required=True)
    up           = Column(type=int, required=True, index=True)
</pre>

Output of python --version:

`Python 3.6.0`

Any idea why this error might be happening?

**Comment by mflaxman** [comment]
I'm guessing that your `redis_connection` didn't have `encoding='utf-8'` as a param when you created it with `create_redis`?

Can you confirm if that's the problem? Thanks!

https://github.com/paxos-bankchain/subconscious/blob/119a8ccb53684f7ae388c295ecfa3b781f3f6565/tests/base.py#L14

**Comment by Quinny** [comment]
Yeah that was the problem.  Thanks a lot.  Great project by the way.
